apiVersion: v1
kind: Service
metadata:
  name: cmf-backend-service
  namespace: default
spec:
  selector:
    app: cmf-backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
