apiVersion: v1
kind: Service
metadata:
  name: cmf-frontend-service
  namespace: default
spec:
  selector:
    app: cmf-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
