import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { downloadPmExcel } from '../../../Maintenance Management Components/pmReportDownload';

export { downloadPmExcel as downloadInventoryExcel };

const BRAND = 'CMF DIGITALIZATION - CMTI';

export function downloadInventoryPdf({ subtitle, metaLines = [], sections, filename }) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let y = 14;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(17, 24, 39);
  doc.text(BRAND, pageWidth / 2, y, { align: 'center' });
  y += 8;

  doc.setFontSize(12);
  doc.setTextColor(74, 108, 247);
  doc.text(subtitle, pageWidth / 2, y, { align: 'center' });
  y += 7;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  metaLines.forEach((line) => {
    doc.text(line, 14, y);
    y += 5;
  });
  y += 3;

  sections.forEach((section, si) => {
    if (y > pageHeight - 24) {
      doc.addPage();
      y = 14;
    }

    if (section.title) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(17, 24, 39);
      doc.text(section.title, 14, y);
      y += 6;
    }

    const colCount = section.headers?.length || 0;
    const isWide = colCount > 10;

    autoTable(doc, {
      head: [section.headers],
      body: section.rows.map((r) => r.map((v) => (v == null || v === '' ? '—' : String(v)))),
      startY: y,
      styles: {
        fontSize: isWide ? 6 : 8,
        cellPadding: isWide ? 1.2 : 2,
        overflow: 'linebreak',
        valign: 'middle',
        lineWidth: 0.1,
        lineColor: [203, 213, 225],
      },
      headStyles: {
        fillColor: [74, 108, 247],
        textColor: 255,
        fontStyle: 'bold',
        fontSize: isWide ? 5.5 : 8,
        halign: 'center',
        valign: 'middle',
      },
      bodyStyles: {
        halign: 'left',
      },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      margin: { left: 6, right: 6 },
      theme: 'grid',
      horizontalPageBreak: isWide,
      horizontalPageBreakRepeat: isWide ? 1 : 0,
      showHead: 'everyPage',
    });

    y = (doc.lastAutoTable?.finalY ?? y) + (si < sections.length - 1 ? 8 : 0);
  });

  doc.setFontSize(7);
  doc.setTextColor(156, 163, 175);
  doc.text('Generated by CMF Inventory Module', pageWidth - 6, pageHeight - 6, { align: 'right' });
  doc.save(`${filename}.pdf`);
}

export function buildTransactionHistoryReportConfig(rows, metaLines = []) {
  const exportRows = rows.map((r, i) => [
    i + 1,
    r.tool_name || '—',
    r.tool_range || '—',
    r.identification_code || '—',
    r.project_name || '—',
    r.product_name || '—',
    r.part_name || '—',
    r.part_number || '—',
    r.operation_name || '—',
    r.operation_number || '—',
    r.requested_qty ?? '—',
    r.requested_by || '—',
    formatExportDateTime(r.request_created_at),
    r.approved_by || '—',
    r.request_status && r.request_status.toLowerCase() !== 'pending'
      ? formatExportDateTime(r.request_updated_at) : '—',
    (r.request_status || '—').toUpperCase(),
    r.returned_qty ?? '—',
    r.collected_by || '—',
    r.return_created_at ? formatExportDateTime(r.return_created_at) : '—',
    r.return_status && r.return_status.toLowerCase() === 'collected'
      ? formatExportDateTime(r.return_updated_at) : '—',
    r.return_status ? r.return_status.toUpperCase() : 'NO RETURNS',
  ]);

  return {
    subtitle: 'Inventory — Transaction History Report',
    metaLines: [
      ...metaLines,
      `Total rows: ${exportRows.length}`,
      `Generated on: ${new Date().toLocaleString('en-IN')}`,
    ],
    sections: [{
      headers: [
        'SL', 'TOOL', 'RANGE', 'ID CODE', 'PROJECT', 'PRODUCT',
        'PART', 'PART NO', 'OPERATION', 'OP NO', 'REQ QTY', 'REQ BY',
        'REQ AT', 'APPR BY', 'APPR AT', 'REQ STATUS',
        'RET QTY', 'COLL BY', 'RET AT', 'COLL AT', 'RET STATUS',
      ],
      rows: exportRows,
    }],
    filename: `inventory-transaction-history-${Date.now()}`,
  };
}

function formatExportDateTime(dateString) {
  if (!dateString) return '—';
  const date = new Date(dateString);
  if (Number.isNaN(date.getTime())) return '—';
  const day = String(date.getDate()).padStart(2, '0');
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const year = date.getFullYear();
  const hours = String(date.getHours()).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');
  return `${day}/${month}/${year} ${hours}:${minutes}`;
}
